services:
  www:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./app:/www/app
      - ./components:/www/components
    networks:
      - internal
    restart: unless-stopped
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: hedwig
    # volumes:
    #   - ./:/docker-entrypoint-initdb.d
    networks:
      - internal
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jakubkawka2005@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    links:
      - postgresql
    networks:
      - internal
    restart: unless-stopped
networks:
  internal:
    driver: bridge
